{{- if eq .Values.scenario "dcups" }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: esp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: esp
  template:
    metadata:
      labels:
        app: esp
    spec:
      containers:
        - name: esp
        {{- if .Values.development.useDevImages }}
          image: {{ .Values.esp.image.devRepository }}:{{ .Values.esp.image.tag }}
          {{- else }}
          image: {{ .Values.esp.image.repository }}:{{ .Values.esp.image.tag }}
        {{- end }}
          imagePullPolicy: IfNotPresent
          {{- if .Values.esp.privileged }}
          securityContext:
            privileged: true
          {{- end }}
          ports:
            - containerPort: 9111
            - containerPort: 9191
            {{- if .Values.development.debugEndpointsEnabled }}
            - containerPort: 32500
            {{- end }}
          env:
            - name: MICROSERVICE_LABEL
              value: {{ .Values.esp.serviceLabel }}
          {{- if .Values.probes.enabled }}
          readinessProbe:
            httpGet:
              path: /readiness
              port: 9191
              {{- if .Values.esp.http.secureTransport }}
              scheme: HTTPS
              httpHeaders:
                - name: Authorization
                  value: "Basic {{ .Values.esp.http.secrets.basicAuth | b64enc }}"
              {{- end }}
            periodSeconds: {{ .Values.probes.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.failureThreshold }}
            initialDelaySeconds: {{ .Values.probes.readinessInitialDelaySeconds }}
          livenessProbe:
            httpGet:
              path: /liveness
              port: 9191
              {{- if .Values.esp.http.secureTransport }}
              scheme: HTTPS
              httpHeaders:
                - name: Authorization
                  value: "Basic {{ .Values.esp.http.secrets.basicAuth | b64enc }}"
              {{- end }}
            periodSeconds: {{ .Values.probes.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.failureThreshold }}
            initialDelaySeconds: {{ .Values.probes.livenessInitialDelaySeconds }}
          {{- end }}
          volumeMounts:
            - name: agent-config
              mountPath: /opt/esp-agent/dev
            - name: kiknosctl-config
              mountPath: /root/.agentctl/
            - name: memif-sockets
              mountPath: {{ .Values.vswitch.memifSocketDir }}
            - name: vpp-config
              mountPath: /etc/vpp/vpp.conf
              subPath: vpp.conf
            {{- if .Values.etcd.secureTransport }}
            - name: etcd-secrets
              mountPath: /var/etcd/secrets
            {{- end }}
            {{- if .Values.esp.http.secureTransport }}
            - name: http-secrets
              mountPath: /var/http/secrets
            {{- end }}
            {{- if .Values.development.sourceDirMount.enabled }}
            - name: source-dir
              mountPath: {{ .Values.development.sourceDirMount.containerPath }}
            {{- end }}
          {{- if .Values.esp.hugePages.enabled }}
          resources:
            limits:
              hugepages-2Mi: {{ .Values.esp.hugePages.size }}
              memory: {{ .Values.esp.hugePages.size }}
          {{- end }}
      volumes:
        - name: agent-config
          configMap:
            name: esp-agent-cfg
        - name: kiknosctl-config
          configMap:
            name: esp-kiknosctl-cfg
        - name: memif-sockets
          hostPath:
            path: {{ .Values.vswitch.memifSocketDir }}
        - name: vpp-config
          configMap:
            name: kiknos-vpp-cfg
        {{- if .Values.etcd.secureTransport }}
        - name: etcd-secrets
          secret:
            secretName: {{ .Values.etcd.secrets.secretName }}
        {{- end }}
        {{- if .Values.esp.http.secureTransport }}
        - name: http-secrets
          secret:
            secretName: {{ .Values.esp.http.secrets.secretName }}
        {{- end }}
        {{- if .Values.development.sourceDirMount.enabled }}
        - name: source-dir
          hostPath:
            path: {{ .Values.development.sourceDirMount.hostPath }}
        {{- end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: esp-agent-cfg
data:
  vpp-ifplugin.conf: |
    #publish-statistics: [etcd]
  {{- if not .Values.esp.logs.txnSummary }}
  kvscheduler.conf: |
    print-txn-summary: false
  {{- end }}
  etcd.conf: |
    endpoints:
      {{- if .Values.etcd.useExternalEtcd }}
      - "{{ .Values.etcd.externalEtcdEndpoint }}"
      {{- else }}
      - {{ .Values.etcd.serviceName }}:2379
      {{- end }}
    {{- if .Values.etcd.secureTransport }}
    insecure-transport: false
    cert-file: /var/etcd/secrets/{{ .Values.etcd.secrets.clientCertFile }}
    key-file: /var/etcd/secrets/{{ .Values.etcd.secrets.clientKeyFile }}
    ca-file: /var/etcd/secrets/{{ .Values.etcd.secrets.caCertFile }}
    {{- else }}
    insecure-transport: true
    {{- end }}
    dial-timeout: 10000000000
    allow-delayed-start: true
  grpc.conf: |
    endpoint: 0.0.0.0:9111
    {{- if .Values.esp.http.secureTransport }}
    insecure-transport: false
    cert-file: /var/http/secrets/{{ .Values.esp.http.secrets.serverCertFile }}
    key-file: /var/http/secrets/{{ .Values.esp.http.secrets.serverKeyFile }}
    ca-files:
      - /var/http/secrets/{{ .Values.esp.http.secrets.caCertFile }}
    {{- else }}
    insecure-transport: true
    {{- end }}
    network: tcp
    max-msg-size: 4096
  http.conf: |
    endpoint: 0.0.0.0:9191
    {{- if .Values.esp.http.secureTransport }}
    server-cert-file: /var/http/secrets/{{ .Values.esp.http.secrets.serverCertFile }}
    server-key-file: /var/http/secrets/{{ .Values.esp.http.secrets.serverKeyFile }}
    client-basic-auth:
      - {{ .Values.esp.http.secrets.basicAuth | quote }}
    {{- end }}
  kiknos.conf: |
    KiknosConfig:
      {{- if eq ($.Values.ike.replicas|int) 1 }}
      remoteAgentLabel: ["{{ .Values.ike.serviceLabel }}"]
      {{- else }}
      remoteAgentLabel: [
      {{- range $i, $e := untilStep 1 ($.Values.ike.replicas|add 1|int) 1 -}}
      "{{ $.Values.ike.serviceLabel }}-{{ $e }}"{{ if lt $e $.Values.ike.replicas }},{{ end }}
      {{- end -}}
      ]
      {{- end }}
      {{- if .Values.esp.http.secureTransport }}
      remoteClientCAFile: /var/http/secrets/{{ .Values.esp.http.secrets.caCertFile }}
      remoteClientCertFile: /var/http/secrets/{{ .Values.esp.http.secrets.clientCertFile }}
      remoteClientKeyFile: /var/http/secrets/{{ .Values.esp.http.secrets.clientKeyFile }}
      {{- end }}
  supervisor.conf: |
    programs:
      - name: "vpp"
        executable-path: "/usr/bin/vpp"
        executable-args: ["-c", "/etc/vpp/vpp.conf"]
      - name: "esp-agent"
        executable-path: "{{if.Values.development.useDevImages}}/go/bin/{{else}}/usr/bin/{{end}}esp-agent"
        executable-args: ["--config-dir=/opt/esp-agent/dev"]
    hooks:
      - cmd: "/usr/bin/init_hook.sh"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: esp-kiknosctl-cfg
data:
  config.yml: |
    etcd-endpoints:
    {{- if .Values.etcd.useExternalEtcd }}
      - "{{ .Values.etcd.externalEtcdEndpoint }}"
    {{- else }}
      - {{ .Values.etcd.serviceName }}:2379
    {{- end }}
    etcd-dial-timeout: 20000000000
    {{- if .Values.etcd.secureTransport }}
    kvdb-tls:
      cert-file: /var/etcd/secrets/{{ .Values.etcd.secrets.clientCertFile }}
      key-file: /var/etcd/secrets/{{ .Values.etcd.secrets.clientKeyFile }}
      ca-file: /var/etcd/secrets/{{ .Values.etcd.secrets.caCertFile }}
    {{- end }}
    {{- if .Values.esp.http.secureTransport }}
    http-tls:
      ca-file: /var/http/secrets/{{ .Values.esp.http.secrets.caCertFile }}
    http-basic-auth: {{ .Values.esp.http.secrets.basicAuth | quote }}
    grpc-tls:
      cert-file: /var/http/secrets/{{ .Values.esp.http.secrets.clientCertFile }}
      key-file: /var/http/secrets/{{ .Values.esp.http.secrets.clientKeyFile }}
      ca-file: /var/http/secrets/{{ .Values.esp.http.secrets.caCertFile }}
    {{- end }}

{{- if .Values.development.debugEndpointsEnabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: esp-debug
spec:
  type: NodePort
  selector:
    app: esp
  ports:
    - name: esp-dlv
      port: 32500
      nodePort: 32500
{{- end }}

{{- if .Values.addons.prometheus.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: esp-prometheus
spec:
  selector:
    app: esp
  ports:
    - name: esp-prometheus
      port: 9191
{{- end }}

{{- if and .Values.esp.http.secureTransport .Values.esp.http.secrets.loadFromFiles }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.esp.http.secrets.secretName }}
data:
  {{ .Values.esp.http.secrets.caCertFile }}: |-
    {{ .Files.Get (printf "secrets/%s" .Values.esp.http.secrets.caCertFile) | b64enc }}
  {{ .Values.esp.http.secrets.serverCertFile }}: |-
    {{ .Files.Get (printf "secrets/%s" .Values.esp.http.secrets.serverCertFile) | b64enc }}
  {{ .Values.esp.http.secrets.serverKeyFile }}: |-
    {{ .Files.Get (printf "secrets/%s" .Values.esp.http.secrets.serverKeyFile) | b64enc }}
  {{ .Values.esp.http.secrets.clientCertFile }}: |-
    {{ .Files.Get (printf "secrets/%s" .Values.esp.http.secrets.clientCertFile) | b64enc }}
  {{ .Values.esp.http.secrets.clientKeyFile }}: |-
    {{ .Files.Get (printf "secrets/%s" .Values.esp.http.secrets.clientKeyFile) | b64enc }}
{{- end }}

{{- end }}