---

registry: docker.io
org: networkservicemesh
tag: latest
pullPolicy: IfNotPresent

nsm:
  app: ucnf-client

replicaCount: 4

image:
  repository: networkservicemesh
  tag: latest
  pullPolicy: IfNotPresent
